### ISSUE TITLE
JavaScript Error on Start

### ISSUE THREAD

**Issue by FatherOfAlways** [Fmstrat/pushover-desktop#3]
Immediately upon launching the app I get the following error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
at Object.createTrayIcon (/Applications/Pushover.app/Contents/Resources/app/lib/webpack:/nativefier-placeholder/src/components/trayIcon.ts:13:32)
at App.<anonymous> (/Applications/Pushover.app/Contents/Resources/app/lib/webpack:/nativefier-placeholder/src/main.ts:163:5)
at App.emit (events.js:315:20)
```

When I click OK nothing happens, the window stays empty.

I'm using macOS 12.0.1.

**Comment by uhlhosting** [comment]
```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
at Object.createTrayIcon (/Applications/Pushover.app/Contents/Resources/app/lib/webpack:/nativefier-placeholder/src/components/trayIcon.ts:13:32)
at App.<anonymous> (/Applications/Pushover.app/Contents/Resources/app/lib/webpack:/nativefier-placeholder/src/main.ts:163:5)
at App.emit (events.js:315:20)
```

I got the same.
